server:
  port: 3583

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/library?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
#      单个文件上传最大值
      max-file-size: 10MB
#      上传文件的最大值
      max-request-size: 10MB

#日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      #逻辑删除配置
      logic-not-delete-value: 0
      logic-delete-value: 1

  redis:
    port: 6379
    host: localhost



